### ISSUE TITLE
User Story: Admin view

### ISSUE THREAD

**Issue by Crpearce** [Squeaker-2207/squeaker-fe#11]
- [x] As a User, If I am an admin I should be able to view the flagged squeaks section(available on button click)
- [x] As a User, if I am an admin I should be able to approve or deny flagged squeaks
- [x] As a User, if I have reviewed a squeak it should disappear from the list of flagged content
- [x] As a User, I will not be able to see flagged content if I am not an admin
- [x]  As a User, if I click the thumbs up button the reported content should be approved and disappear from the DOM

**Comment by gjcarew** [comment]
We have a property "reports" that shows number of reports and "approved" which indicates whether a reported tweet has been approved or not
